---
# vars file for windowstemplate
# Template Provisioning Variables
template_name:  WinTPL
vmid: 0
pve_storage_id: local-lvm
vm_cores: 2
vm_sockets: 2
vm_memory_mb: 2048
vm_os_type: win11
bridge: vmbr0
# vm_os_type must be valid value per https://pve.proxmox.com/wiki/Qemu/KVM_Virtual_Machines
drive_size_gb: 50
start_at_boot: no
virto_download_url : https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso
virtio_iso_name: virtio_winx64_latest.iso
os_iso_download_url : https://go.microsoft.com/fwlink/p/?LinkID=2195280&clcid=0x409&culture=en-us&country=US
os_iso_location: /mnt/pve/nas-iso/template/iso
os_iso_name: SERVER_EVAL_x64FRE_en-us.iso
format: raw
# qcow2 or raw if on lvm
#agent: enabled=0
# or  
agent: 'enabled=1,fstrim_cloned_disks=1,type=virtio'

# Unattend.xml template variables:
deploy_image: 'Windows Server 2022 SERVERDATACENTER'
# Applicable 2019 options for deploy_image: 
# Windows Server 2019 SERVERDATACENTER, Windows Server 2019 SERVERDATACENTERCORE,
# Windows Server 2019 SERVERSTANDARD, Windows Server 2019 SERVERSTANDARDCORE,
# Applicable 2022 options for deploy_image: 
# Windows Server 2022 SERVERDATACENTER, Windows Server 2022 SERVERDATACENTERCORE,
# Windows Server 2022 SERVERSTANDARD, Windows Server 2022 SERVERSTANDARDCORE
vm_admin_pass: Passw0rd
vm_time_zone: 'Eastern Standard Time'
org_name: 'HowIAutomatedThis'