- name: Test if {{ bastion_os_iso_name }} already exists in {{ bastion_os_iso_location }}
  stat:
    path: "{{ bastion_os_iso_location }}/{{ bastion_os_iso_name }}"
  register: bastion_os_iso

- name: Download {{ bastion_os_iso_name }} to {{ bastion_os_iso_location }}
  get_url:
    url: "{{ bastion_os_iso_url }}"
    dest: "{{ bastion_os_iso_location }}/{{ bastion_os_iso_name }}"
  when: not bastion_os_iso.stat.exists