---

# Description
- name: Pve post installation configuration
  hosts: pve
  gather_facts: true
  vars:
    source_file: ../files/proxmox
  tasks:
    - name: Update config file for windows cloudbase compatibility
    # copy each files in loop
      ansible.builtin.copy:
        src: "{{ source_file }}/{{ item.name }}"
        dest: "{{ item.dest }}/{{ item.name }}"
        owner: root
        group: root
        mode: preserve
        backup: true
      loop:
        - {name: Cloudinit.pm, dest: /usr/share/perl5/PVE/QemuServer/ }
        - {name: Qemu.pm, dest: /usr/share/perl5/PVE/API2/}

    - name: Restart service
      ansible.builtin.service:
        name: pvedaemon.service
        state: restarted

    - name: Correct ProxMox VE Sources
    # The package manager will use the correct sources to update and install packages on your Proxmox VE server
      ansible.builtin.blockinfile:
        path: /etc/apt/sources.list
        block: |
          deb http://deb.debian.org/debian bookworm main contrib
          deb http://deb.debian.org/debian bookworm-updates main contrib
          deb http://security.debian.org/debian-security bookworm-security main contrib
        create: true
        state: present
        mode: '0644'

    - name: Remove 'pve-enterprise' repository
    # This will remove the enterprise repository from the sources list
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        state: absent

    - name: Create 'pve-no-subscription' repository
    # This will create the no subscription repository file
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/pve-install-repo.list
        state: touch
        mode: '0644'
        owner: root
        group: root

    - name: Add 'pve-no-subscription' repository
    # This will add the no subscription repository to the sources list
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/pve-install-repo.list
        line: 'deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription'
        state: present

    - name: Create 'pvetest' repository
    # This will create the pvetest repository file
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/pvetest-for-beta.list
        state: touch
        mode: '0644'
        owner: root
        group: root

    - name: Add (Disabled) 'pvetest' repository
    # This will add the pvetest repository to the sources list
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/pvetest-for-beta.list
        line: '# deb http://download.proxmox.com/debian/pve bookworm pvetest'
        state: present

    - name: Disable subscription nag
      ansible.builtin.replace:
        path: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
        regexp: '(function\(orig_cmd\) \{)'
        replace: '\1\n\torig_cmd();\n\treturn;'
        backup: true

    - name: Updating Proxmox VE (Patience)
    # This will update the Proxmox VE server
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        autoremove: true
        autoclean: true
        force_apt_get: true
        cache_valid_time: 3600

    - name: Install pip
      ansible.builtin.package:
        name:
          - python3-pip
          - python3-proxmoxer
          - vim
          - tree
        state: present
