---

#test le reole de creation d'un template windows
- name: Windows template creation
  hosts: pve
  tasks:
    - name: Test role windows template
      import_role:
        name: roles/windowstemplate