---

#description
- name: Configure DSC Lab
  hosts: dsclab

  tasks:
    - name: Rename server with name in inventory {{ inventory_hostname }}
      ansible.builtin.win_hostname:
        name: "{{ inventory_hostname }}"

    - name: install windows updates on server {{ inventory_hostname }}
      ansible.windows.win_updates:
        category_names: '*'
        reboot: true

    - name: install and configure Active Directory domain on server {{ inventory_hostname }}
      block:
      - name: install AD domain feature on server {{ inventory_hostname }}
        ansible.windows.win_feature:
          name: AD-Domain-Services,DNS
          include_sub_features: yes
          state: present
          include_management_tools: yes

      - name: Create new Windows domain in a new forest with specific parameters and reboot in post task
        microsoft.ad.domain:
          create_dns_delegation: "{{ create_dns_delegation }}"
          database_path: "{{ database_path }}"
          dns_domain_name: "{{ dns_domain_name }}"
          domain_mode: "{{ domain_mode }}"
          domain_netbios_name: "{{ domain_netbios_name }}"
          forest_mode: "{{ forest_mode }}"
          safe_mode_password: "{{ safe_mode_password }}"
          sysvol_path: "{{ sysvol_path }}"
        register: domain_install

      - name: Reboot host if install requires it
        ansible.windows.win_reboot:
        when: domain_install.reboot_required
      when: inventory_hostname == "srvdc01"