- name: Create temp directory
  ansible.builtin.file:
    path: /tmp/{{ template_name }}
    state: directory

- name: Download Virtio iso file
  ansible.builtin.get_url:
    url: '{{ virto_download_url }}'
    dest: '{{ os_iso_location }}/{{ virtio_iso_name }}'
  register: virtio_download_result
  retries: 5
  delay: 2
  until: virtio_download_result is succeeded

# Downlaod windows iso from internet
- name: Download W2K22 iso file
  ansible.builtin.get_url:
    url: '{{ os_iso_download_url }}'
    dest: '{{ os_iso_location }}/{{ os_iso_name }}'
  register: w2k22_download_result
  retries: 5
  delay: 2
  until: w2k22_download_result is succeeded
