- name: Create temp directory
  file:
    path: /tmp/{{template_name}}
    state: directory
    
- name: Download Virtio iso file
  ansible.builtin.get_url:
    url: '{{ virto_download_url }}'
    dest: '/tmp/{{ template_name }}/{{ virtio_iso_name }}'

#downlaod windows iso from internet
- name: Download W2K22 iso file
  ansible.builtin.get_url:
    url: '{{ os_iso_download_url }}'
    dest: '/tmp/{{ template_name }}/{{ os_iso_name }}'

