#
# requirements for Ansible 
#
---
# Install roles from Ansible Galaxy.
roles:
  - name: geerlingguy.java
    version: 2.5.0

# Install collections from Ansible Galaxy.
collections:
  - name: community.general
    version: 9.1.0
  - name: ansible.posix
    version: 1.5.4
  - name: ansible.windows
    version: 2.4.0
  - name: community.windows
    version: 2.2.0